on:
  push:
    branches: [ "new-b" ]
  workflow_dispatch:

env:
  NODE_VERSION: '14.x'                # set this to the node version to use
  PARAPHRASE: "12345678"
  HOME_PATH: $HOME

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: uppload code
      uses: actions/checkout@v3
    - name: Current Dir
      run: pwd
    - name: List Files
      run: | 
        ls -a
        curPath="$(pwd)"
        echo $curPath
    
    - name: Decrypt File
      run: gpg --quiet --batch --yes --decrypt --passphrase=${{env.PARAPHRASE}} --output $HOME/.env .env.gpg
    - name: Print HOME
      run: | 
        echo ${{env.HOME_PATH}}     # this is different than the next line -> /home/runner
        echo $Home/.env/             # -> /.env
        cat $HOME/.env
    
    - name: Expose $Home
      run: |
        ls -a
        curPath="$(pwd)"
        echo $curPath
        sudo cp $HOME/.env $curPath
        cd $curPath               # does not have effect!
        ls -a
      
    - name: List
      run: |
        cd $HOME
        ls -a
    - name: Build
      run: echo "Project Built"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: build-files
        path: |
          /home/runner/work/test-play/test-play
          .env
    - name: Print
      run: |
        ls -a
