on:
  push:
    branches: [ "new-b" ]
  workflow_dispatch:

env:
  NODE_VERSION: '14.x'                # set this to the node version to use
  PARAPHRASE: "12345678"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: uppload code
      uses: actions/checkout@v3
    - name: Current Dir
      run: pwd
    - name: List Files
      run: ls
    
    - name: Decrypt File
      run: gpg --quiet --batch --yes --decrypt --passphrase=${{env.PARAPHRASE}} --output $pwd/env .env.gpg
    - name: Print HOME
      run: cat $HOME/env
    
    - name: Expose $Home
      run: echo $Home
      
    - name: List
      run: |
        cd $HOME
        ls 
    - name: Build
      run: echo "Project Built"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: build-files
        path: |
           $HOME/env