on:
  push:
    branches: [ "new-b" ]
  workflow_dispatch:

env:
  NODE_VERSION: '14.x'                # set this to the node version to use
  PARAPHRASE: "12345678"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: uppload code
      uses: actions/checkout@v3
    - name: decrypt file
      run: gpg --quiet --batch --yes --decrypt --passphrase=${{env.PARAPHRASE}} --output .env2 .env.gpg
    - name: print HOME
      run: echo $HOME